### PR TITLE
Support MPL 1.1 License

### PR DESCRIPTION
**Pull request by shige0501**
Hi. I'd like to use MPL 1.1 License by this plugin.
https://opensource.org/licenses/MPL-1.1

and fixed adjust MPL 2.0.

Thank you.

### CODE REVIEW

**Review by k4zy — APPROVED** [review]

**Comment by k4zy** [comment]
ping @cookpad/mobile-infra

**Review by koyama-kani-daisuki — APPROVED** [review]
LGTM 👍

**Comment by koyama-kani-daisuki** [comment]
Thank you for your contribution. I will release it tomorrow.

**Comment by koyama-kani-daisuki** [comment]
I released v0.20.0. Thanks.

**Pull request merged**
