### PR TITLE
Fix resolved artifacts over android-gradle-plugin 3.0

### PR DESCRIPTION
**Pull request by litmon**
When I execute `./gradlew checkLicenses` before some assemble tasks in my project, it failed.

```
13:47:45 :app:checkLicenses FAILED
13:47:45 
13:47:45 FAILURE: Build failed with an exception.
13:47:45 
13:47:45 * Where:
13:47:45 Build file /workspace/project/app/build.gradle' line: 560
13:47:45 
13:47:45 * What went wrong:
13:47:45 Execution failed for task ':app:checkLicenses'.
13:47:45 > Could not resolve all dependencies for configuration ':app:apiCopy'.
13:47:45    > Could not resolve com.jakewharton.timber:timber:4.6.1.
13:47:45      Required by:
13:47:45          project :app
13:47:45       > Could not resolve com.jakewharton.timber:timber:4.6.1.
13:47:45          > Could not get resource 'https://jcenter.bintray.com/com/jakewharton/timber/timber/4.6.1/timber-4.6.1.pom'.
13:47:45             > java.lang.reflect.UndeclaredThrowableException (no error message)
```

However It succeeded after assemble task.

I fixed the issue to use `resolvedConfiguration.lenientConfiguration.artifacts` instead of `resolvedConfiguration.resolvedArtifacts`.
Because `resolvedArtifacts` "probably" could be allowed access after artifacts resolved. (I could not understand why it run correctly...)
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ResolvedConfiguration.html

### CODE REVIEW

**Comment by litmon** [comment]
test this please

**Comment by KazuCocoa** [comment]
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/LenientConfiguration.html#getArtifacts--
The method only gets artefacts can be resolved. If something fails, the method ignores them. So, only succeeded artefacts remain..

**Review by ghost — APPROVED** [review]

**Comment by litmon** [comment]
https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/LenientConfiguration.html#getUnresolvedModuleDependencies--
this method returns unresolved dependencies, so I will try to add the validation it is empty.

**Comment by litmon** [comment]
When I tried `LenientConfiguration.unresolvedModuleDependencies()`, the returned object contains sub module project.
Sub module dependencies already got so I will ignore unresolvedModuleDependencies.

And I noticed that workaround for android-gradle-plugin 3.0( https://github.com/cookpad/license-tools-plugin/pull/85 ) is not necessary after using `LenientConfiguration.artifacts`.
I also noticed current master revision causes that `./gradlew checkLicenses` succeed but `./gradlew :example:checkLicenses` fail because missing libraries in licenses.yml.
So I will revert PR https://github.com/cookpad/license-tools-plugin/pull/85

**Comment by KazuCocoa** [comment]
🆒 
We'll no longer need the workaround.

**Comment by ghost** [comment]
:note:

We should avoid https://stackoverflow.com/questions/45679847/android-studio-3-0-compile-issue-cannot-choose-between-configurations workaround, setting _default_ like `implementation project(path: ':example-dep', configuration: 'default')`.

**Pull request merged**
