### PR TITLE
Add license url

### PR DESCRIPTION
**Pull request by knordbo**
Pull request for: https://github.com/cookpad/license-tools-plugin/issues/27

Adding license url as part of the data in .yml and .json

### CODE REVIEW

**Comment by gfx** [comment]
LGTM

**Comment by gfx** [comment]
@komatatsu Can you release a new version?

**Comment by komatatsu** [comment]
okay, i will try next week

**Comment by knordbo** [comment]
Would appreciate if you ping/mention me when this is released! Cheers

**Comment by komatatsu** [comment]
sure

**Comment by komatatsu** [comment]
@knordbo v0.18.0 is released.
thanks for your contribution.

**Pull request merged**
