### PR TITLE
Add updatelicense task for auto addition of licenses to  `licenses.yml`

### PR DESCRIPTION
**Pull request by iamutkarshtiwari**
This PR is just an updated version of this exisiting [one](https://github.com/cookpad/license-tools-plugin/pull/60)

### CODE REVIEW

**Comment by iamutkarshtiwari** [comment]
@gfx @litmon @KazuCocoa  Please have a look at this 🙇

**Review by KazuCocoa — APPROVED** [review]
sorry for late review.
Let me merge tomorrow.

**Review by koyama-kani-daisuki — APPROVED** [review]
Thanks! :crab:

**Comment by iamutkarshtiwari** [comment]
@KazuCocoa @nein37 Thank you for your prompt response. When are you planning to release this change in a new version? Really excited to try it out in my project :)

**Comment by ghost** [comment]
Yup, it will release in a day

**Comment by iamutkarshtiwari** [comment]
@kazu-matsu Thank you so much!

**Comment by litmon** [comment]
released v1.3.0 👍

**Comment by iamutkarshtiwari** [comment]
@litmon @kazu-matsu @KazuCocoa  What could be the cause for this issue? - 

```
./gradlew updateLicenses

> Configure project :example 
example: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'com.android.databinding:compiler:3.0.0'.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':example:updateLicenses'.
> Could not resolve all dependencies for configuration ':example:implementationCopy'.
   > Could not resolve project :example-dep.
     Required by:
         project :example
      > Cannot choose between the following configurations of project :example-dep:
          - debugApiElements
          - debugRuntimeElements
          - releaseApiElements
          - releaseRuntimeElements
        All of them match the consumer attributes:
          - Configuration 'debugApiElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
          - Configuration 'debugRuntimeElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.
          - Configuration 'releaseApiElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
          - Configuration 'releaseRuntimeElements':
              - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
              - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
              - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org


```

**Comment by ghost** [comment]
You need to add `updateLicenses` to https://github.com/cookpad/license-tools-plugin/blob/master/example/build.gradle#L73-L82 . The cause is : https://github.com/cookpad/license-tools-plugin#for-gradle-plugin-3-users , I believe.

**Pull request merged**
