### PR TITLE
generateLicenseJson task

### LINKED ISSUE #23: JSON output
the HTML output is good, but not very configurable.
With an option for JSON output, developers using the library could implement a ListView or RecyclerView to show the output formatted appropriately.

### PR DESCRIPTION
**Pull request by vishna**
closes #23

### CODE REVIEW

**Comment by gfx** [comment]
Great! Can you run `./gradlew generateLicenseJson` and commit the result? Just like as https://github.com/cookpad/license-tools-plugin/blob/master/example/src/main/assets/licenses.html

**Comment by vishna** [comment]
updated my commit

**Comment by vishna** [comment]
device-2016-07-13-185611

**Comment by gfx** [comment]
Thanks. LGTM.

**Pull request merged**
