### PR TITLE
Generate licenses.html with the same library order in licenses.yml

### PR DESCRIPTION
**Pull request by rockwillj**
Unfortunately tracking SDK is placed at the top of licenses.html in my module, such as Adjust SDK and AdWords SDK.
I want to place modern libraries instead at the top, such as RxJava2, Dagger2, Retrofit and Kotlin.

If you want previous order in licenses.html, you just write libraries alphabetically order in licenses.yml.

### TODO

- [x] Update `assets/licenses.html` and `assets/licenses.json`

### CODE REVIEW

**Review by litmon — APPROVED** [review]
I think it is good change, how about? @uzzu @nein37

**Review by uzzu — APPROVED** [review]
LGTM

**Comment by koyama-kani-daisuki** [comment]
Could you update `example/src/main/assets/licenses.html` and `example/src/main/assets/licenses.json` ?

**Comment by rockwillj** [comment]
@nein37 OK, I will do it but #50 must be conflicted with this. Please wait until #50 merged (I hope).

**Comment by uzzu** [comment]
#50 merged 😄

**Comment by rockwillj** [comment]
@uzzu thanks a lot! I updated both `licenses.html` and `licenses.json`.

**Comment by uzzu** [comment]
I confirmed generated files. It's ok.

**Pull request merged**
